#!/usr/bin/env node
/**
 * SessionReaper 打包脚本：把 src/*.js 原样复制到 lib/，并加上「勿手改」头。
 *
 * 本插件是纯宿主插件，没有浏览器半边，因此不需要 DSH 客户端模块外壳，
 * 也不需要任何第三方打包器。lib/index.js 就是 Loader 直接 import 的入口。
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const header = "// Generated by scripts/build.mjs from src/ - do not edit by hand.\n";
const modules = ["core.js", "index.js"];

mkdirSync(join(root, "lib"), { recursive: true });
for (const name of modules) {
  const source = readFileSync(join(root, "src", name), "utf8");
  writeFileSync(join(root, "lib", name), header + source);
  console.log("built lib/" + name + " (" + source.length + " bytes) for " + pkg.name);
}
