#!/usr/bin/env node
/**
 * TokenPurse 打包脚本：把 src/client.js 包进 DSH 客户端模块加载器外壳。
 *
 * DSH 浏览器端用 window.__ModuleLoader__.load({ id, factory }) 登记每个客户端
 * 插件的「工厂」，工厂体在首次 import 时执行，其中的 require() 由模块表解析。
 * 本脚本只做文本包裹，不引入任何依赖，产物 lib/client.js 会被宿主的
 * dsh-client-modules 直接读取，并作为 /plugins/<id>/client.js 提供。
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const source = readFileSync(join(root, "src", "client.js"), "utf8");

const indent = (text) =>
  text
    .split(/\r?\n/)
    .map((line) => (line.length > 0 ? "\t\t" + line : line))
    .join("\n");

const header = "// Generated by scripts/build.mjs from src/client.js - do not edit by hand.";
const lines = [
  header,
  "window.__ModuleLoader__.load({",
  "\tid: " + JSON.stringify(pkg.name) + ",",
  "\tfactory: (require) => {",
  "\t\tvar module = { exports: {} };",
  "\t\tvar exports = module.exports;",
  "\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: \"Module\" });",
  indent(source),
  "\t\treturn module.exports;",
  "\t}",
  "});",
  ""
];
const bundle = lines.join("\n");

mkdirSync(join(root, "lib"), { recursive: true });
writeFileSync(join(root, "lib/client.js"), bundle);
console.log("built lib/client.js (" + bundle.length + " bytes) for " + pkg.name);